version: "3.8"

services:
  python-app:
    build: ./app
    container_name: python-app
    ports:
      - "5000:5000"  
    networks:
      - demo-net

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "8080:80"
    depends_on:
      - python-app
    networks:
      - demo-net

networks:
  demo-net:
    driver: bridge
